const sql = `
CREATE TABLE IF NOT EXISTS radiolinie_tmp (
	"L.p." int4 NULL,
	dl_geo_tx varchar(50) NULL,
	sz_geo_tx varchar(50) NULL,
	"H_t_Tx [m npm]" varchar(50) NULL,
	"Miejscowość Tx" varchar(50) NULL,
	"Województwo Tx" varchar(50) NULL,
	"Ulica Tx" varchar(64) NULL,
	"Opis położenia Tx" varchar(64) NULL,
	dl_geo_rx varchar(50) NULL,
	sz_geo_rx varchar(50) NULL,
	"H_t_Rx [m npm]" varchar(50) NULL,
	"Miejscowość Rx" varchar(50) NULL,
	"Województwo Rx" varchar(50) NULL,
	"Ulica Rx" varchar(64) NULL,
	"Opis położenia Rx" varchar(64) NULL,
	"f [GHz]" varchar(50) NULL,
	nr_kan varchar(50) NULL,
	symbol_planu varchar(50) NULL,
	"Szer_kan [MHz]" varchar(50) NULL,
	polaryzacja varchar(50) NULL,
	"Rodz_modu-lacji" varchar(50) NULL,
	"Przepływność [Mb/s]" varchar(50) NULL,
	"EIRP [dBm]" varchar(50) NULL,
	"Tłum_ant_odb_Rx [dB]" varchar(50) NULL,
	typ_nad varchar(50) NULL,
	prod_nad varchar(50) NULL,
	"Liczba_szum_Rx [dB]" varchar(50) NULL,
	"Tłum_ATPC [dB]" varchar(50) NULL,
	typ_ant_tx varchar(50) NULL,
	prod_ant_tx varchar(50) NULL,
	"Zysk_ant_Tx [dBi]" varchar(50) NULL,
	"H_ant_Tx [m npt]" varchar(50) NULL,
	typ_ant_rx varchar(50) NULL,
	prod_ant_rx varchar(50) NULL,
	"Zysk_ant_Rx [dBi]" varchar(50) NULL,
	"H_ant_Rx [m npt]" varchar(50) NULL,
	"Operator" varchar(128) NULL,
	"Nr_pozw/dec" varchar(50) NULL,
	rodz_dec varchar(50) NULL,
	data_wydania varchar(50) NULL,
	"Data_ważn_pozw/dec" varchar(50) NULL
);

CREATE TABLE IF NOT EXISTS radiolinie (
	"L.p." int4 NULL,
	dl_geo_tx varchar(12) NULL,
	sz_geo_tx varchar(12) NULL,
	"H_t_Tx [m npm]" varchar(10) NULL,
	"Miejscowość Tx" varchar(50) NULL,
	"Województwo Tx" varchar(20) NULL,
	"Ulica Tx" varchar(64) NULL,
	"Opis położenia Tx" varchar(64) NULL,
	dl_geo_rx varchar(12) NULL,
	sz_geo_rx varchar(12) NULL,
	"H_t_Rx [m npm]" varchar(10) NULL,
	"Miejscowość Rx" varchar(50) NULL,
	"Województwo Rx" varchar(20) NULL,
	"Ulica Rx" varchar(64) NULL,
	"Opis położenia Rx" varchar(64) NULL,
	"f [GHz]" varchar(10) NULL,
	nr_kan varchar(10) NULL,
	symbol_planu varchar(25) NULL,
	"Szer_kan [MHz]" varchar(5) NULL,
	polaryzacja varchar(2) NULL,
	"Rodz_modu-lacji" varchar(15) NULL,
	"Przepływność [Mb/s]" varchar(20) NULL,
	"EIRP [dBm]" varchar(10) NULL,
	"Tłum_ant_odb_Rx [dB]" varchar(20) NULL,
	typ_nad varchar(50) NULL,
	prod_nad varchar(50) NULL,
	"Liczba_szum_Rx [dB]" varchar(10) NULL,
	"Tłum_ATPC [dB]" varchar(10) NULL,
	typ_ant_tx varchar(50) NULL,
	prod_ant_tx varchar(50) NULL,
	"Zysk_ant_Tx [dBi]" varchar(10) NULL,
	"H_ant_Tx [m npt]" varchar(10) NULL,
	typ_ant_rx varchar(50) NULL,
	prod_ant_rx varchar(50) NULL,
	"Zysk_ant_Rx [dBi]" varchar(10) NULL,
	"H_ant_Rx [m npt]" varchar(10) NULL,
	"Operator" varchar(128) NULL,
	"Nr_pozw/dec" varchar(20) NULL,
	rodz_dec varchar(10) NULL,
	data_wydania varchar(14) NULL,
	"Data_ważn_pozw/dec" varchar(14) NULL,
	stan_na_dzien varchar(14) NULL,
	tx public.geometry NULL,
	rx public.geometry NULL,
	line public.geometry NULL,
	color cube NULL,
	id SERIAL PRIMARY KEY 
);

`;

export default sql;