const sql = `
CREATE TABLE IF NOT EXISTS radiolinie_tmp (
	"L.p." int4 NULL,
	dl_geo_tx varchar NULL,
	sz_geo_tx varchar NULL,
	"H_t_Tx [m npm]" varchar NULL,
	"Miejscowość Tx" varchar NULL,
	"Województwo Tx" varchar NULL,
	"Ulica Tx" varchar NULL,
	"Opis położenia Tx" varchar NULL,
	dl_geo_rx varchar NULL,
	sz_geo_rx varchar NULL,
	"H_t_Rx [m npm]" varchar NULL,
	"Miejscowość Rx" varchar NULL,
	"Województwo Rx" varchar NULL,
	"Ulica Rx" varchar NULL,
	"Opis położenia Rx" varchar NULL,
	"f [GHz]" varchar NULL,
	nr_kan varchar NULL,
	symbol_planu varchar NULL,
	"Szer_kan [MHz]" varchar NULL,
	polaryzacja varchar NULL,
	"EIRP [dBm]" varchar NULL,
	"H_ant_Tx [m npt]" varchar NULL,
	"H_ant_Rx [m npt]" varchar NULL,
	"Operator" varchar NULL,
	"Nr_pozw/dec" varchar NULL,
	rodz_dec varchar NULL,
	data_wydania varchar NULL,
	"Data_ważn_pozw/dec" varchar NULL
);

CREATE TABLE IF NOT EXISTS radiolinie (
	"L.p." int4 NULL,
	dl_geo_tx varchar NULL,
	sz_geo_tx varchar NULL,
	"H_t_Tx [m npm]" varchar NULL,
	"Miejscowość Tx" varchar NULL,
	"Województwo Tx" varchar NULL,
	"Ulica Tx" varchar NULL,
	"Opis położenia Tx" varchar NULL,
	dl_geo_rx varchar NULL,
	sz_geo_rx varchar NULL,
	"H_t_Rx [m npm]" varchar NULL,
	"Miejscowość Rx" varchar NULL,
	"Województwo Rx" varchar(20) NULL,
	"Ulica Rx" varchar NULL,
	"Opis położenia Rx" varchar NULL,
	"f [GHz]" varchar NULL,
	nr_kan varchar NULL,
	symbol_planu varchar NULL,
	"Szer_kan [MHz]" varchar NULL,
	polaryzacja varchar NULL,
	"EIRP [dBm]" varchar NULL,
	"H_ant_Tx [m npt]" varchar NULL,
	"H_ant_Rx [m npt]" varchar NULL,
	"Operator" varchar NULL,
	"Nr_pozw/dec" varchar NULL,
	rodz_dec varchar NULL,
	data_wydania varchar NULL,
	"Data_ważn_pozw/dec" varchar NULL,
	stan_na_dzien varchar NULL,
	tx public.geometry NULL,
	rx public.geometry NULL,
	line public.geometry NULL,
	color cube NULL,
	id SERIAL PRIMARY KEY 
);

`;

export default sql;